### ISSUE TITLE
Image viewer fatally errors at random BMPs

### ISSUE THREAD

**Issue by ca1ek** [redox-os/orbutils#3]
**Reproduction**: Run Redox, then open BMPs until it happens

**Expected behavior**: No crashes

**Actual behavior**: 
1. [Displays this error message](http://i.imgur.com/3u0diTM.png)
2. Whole OS hangs for about 10 seconds
3. Page fault gets displayed
4. OS keeps being usable but pagefaults on something else, in my case pixelcannon

**Build information**: rustc 1.10.0-nightly (4ec5ce5e4 2016-05-12)

**Misc**: Pagefault output paste: https://gist.github.com/ca1ek/c92131ce037bf61e5b0a0cfd5ffaaeb1

------

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by jackpot51** [comment]
I think this is a problem with ralloc or the kernel, not with orbutils

**Comment by ca1ek** [comment]
New issue for this error over at https://github.com/redox-os/redox/issues/663
